-- Migration 0056: egress_allowlist table.
--
-- Backs the WebFetch egress-gate hook's runtime allowlist, previously a
-- store/egress-allowlist.json side-car ({ domains: [...], prefixes: [...],
-- quarantine_domains: [...] }). Part of the wider config/state -> SQLite
-- migration (#985, plan #984). The hook itself (scripts/hooks/egress-gate.mjs)
-- runs OUTSIDE the backend Node process (a Claude Code PreToolUse hook, spawned
-- fresh per tool call) so it cannot import this table directly -- it calls
-- GET /api/v1/egress-allowlist over HTTP, disk-cached ~30s, with a fall back to
-- reading the JSON file directly if the dashboard is unreachable (decision D1=A,
-- workspace-doc b7c3d4e5f6a048b9c2d1e3f4a5b6c7d8). The file itself is left in place
-- (store/ is gitignored) purely as that fallback -- it is no longer read or
-- written by the backend as the primary source.
--
-- type='quarantine_domain' extends the plan doc's two-value CHECK (domain/prefix)
-- to also cover quarantine_domains -- the hook's own JSON schema has a third list
-- (operator-added domains reachable ONLY by the quarantine-reader sub-agent) that
-- the plan's schema sketch omitted; dropping it here would have been a silent
-- feature loss for anyone who had populated it (this install has none, but a
-- fork elsewhere might).
CREATE TABLE IF NOT EXISTS egress_allowlist (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  value      TEXT    NOT NULL,
  type       TEXT    NOT NULL CHECK(type IN ('domain', 'prefix', 'quarantine_domain')),
  added_by   TEXT    NOT NULL DEFAULT 'system',
  added_at   INTEGER NOT NULL DEFAULT (unixepoch()),
  tenant_id  TEXT    NOT NULL DEFAULT 'default',
  UNIQUE(value, type, tenant_id)
);

-- Seed: the 199 domains from this install's store/egress-allowlist.json at
-- migration-authoring time (2026-09-29). INSERT OR IGNORE per row (not a
-- table-level "is it empty" guard) so an operator's later edit is never
-- overwritten by a --force-reapply, and so a fresh install that never had the
-- JSON file still gets the same starting allowlist (same rationale as migration
-- 0053's autonomy_categories seed).
INSERT OR IGNORE INTO egress_allowlist (value, type, added_by, added_at, tenant_id)
VALUES
  ('github.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.github.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('api.github.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.dcrainmaker.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('dcrainmaker.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.volvocars.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('volvocars.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.landrover.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('landrover.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.jeep.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('jeep.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.autonavigator.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('autonavigator.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.totalcar.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('totalcar.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.vezess.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('vezess.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.arukereso.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('arukereso.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('evadatbazis.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.evadatbazis.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('premium-cars.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.premium-cars.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('volvo.schneiderautohaz.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('hovanyvolvocars.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('carlab.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.carlab.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('kocsi.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.kocsi.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('jeepszabo.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.jeepszabo.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('4x4magazin.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.4x4magazin.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('autoaddikt.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.autoaddikt.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('joautok.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.joautok.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('carnet.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.carnet.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('ultimatespecs.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.ultimatespecs.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('machinelearningmastery.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.machinelearningmastery.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('kia.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.kia.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('hyundai.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.hyundai.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('media.hyundai.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('toyota.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.toyota.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('pdf.sites.toyota.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('sites.toyota.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('lexus.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.lexus.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('content.lexus-ce.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('schiller.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.schiller.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('lexusbuda.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.lexusbuda.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('lexusmonor.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.lexusmonor.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('toyotabalogh.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.toyotabalogh.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('toyotakovacs.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.toyotakovacs.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('katalogus.hasznaltauto.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('hasznaltauto.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.hasznaltauto.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('renault.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.renault.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('autowallis.renault.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('szabo.renault.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('cdn.group.renault.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('dacia.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.dacia.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('ford.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.ford.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('fordszabo.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.fordszabo.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('autocentrumszabo.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.autocentrumszabo.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('acszabo.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('hovany.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.hovany.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('petranyiauto.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.petranyiauto.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('mazda.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.mazda.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('suzuki.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.suzuki.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('novaauto.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.novaauto.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('tesztelok.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.tesztelok.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('automobiledimension.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.automobiledimension.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('howtogeek.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.howtogeek.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('aimit.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.aimit.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('jonasgergo.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.jonasgergo.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('interactivebrokers.ie', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.interactivebrokers.ie', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('vaylostudios.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.vaylostudios.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('conducting.ai', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.conducting.ai', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('zoeyos.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.zoeyos.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('skillsdirectory.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.skillsdirectory.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('claudeskills.org', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.claudeskills.org', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('raw.githubusercontent.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('rendeljkinait.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.rendeljkinait.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('code.claude.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.code.claude.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('bearmybrand.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.bearmybrand.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('ogyei.gov.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.ogyei.gov.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('nnk.gov.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.nnk.gov.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('nngyk.gov.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.nngyk.gov.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('ema.europa.eu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.ema.europa.eu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('who.int', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.who.int', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('neak.gov.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.neak.gov.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('pubmed.ncbi.nlm.nih.gov', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('ncbi.nlm.nih.gov', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.ncbi.nlm.nih.gov', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('medlineplus.gov', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.medlineplus.gov', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('claude.ai', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('preview.claude.ai', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('reddit.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.reddit.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('politico.eu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.politico.eu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('adatbazis.k-monitor.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('k-monitor.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.companywall.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('companywall.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('ceginfo.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.ceginfo.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('telex.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.telex.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('help.uptimerobot.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.help.uptimerobot.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('uptimerobot.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.uptimerobot.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.hetzner.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('hetzner.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('docs.hetzner.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('webhosting.de', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.webhosting.de', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('net.jogtar.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.net.jogtar.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('nki.gov.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.nki.gov.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('allegro.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.allegro.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('integracio.szamlazz.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('szamlazz.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.szamlazz.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('api.frankfurter.app', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('frankfurter.app', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('api.frankfurter.dev', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('frankfurter.dev', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('mnb.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.mnb.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('ironmanczech.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.ironmanczech.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('eu.ironman.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.ironman.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('linkedin.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.linkedin.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('eur-lex.europa.eu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.naih.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('naih.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('aihirfolyam.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('prog.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('pcforum.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('sg.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('kiszamolo.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('prohardver.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('techlabor.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('techkalauz.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('ekr.gov.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.ekr.gov.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('kozbeszerzes.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('www.kozbeszerzes.hu', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('hu.openprocurements.com', 'domain', 'seed_migration', unixepoch(), 'default'),
  ('openprocurements.com', 'domain', 'seed_migration', unixepoch(), 'default');
